### ISSUE TITLE
chart date range selection

### ISSUE THREAD

**Issue by sandikbarr** [PRX/chart.prx.org#13]
Users would like to view metrics data over different periods of time such as the last week, the last two weeks, the last month, the last 3 months, the last year, all time, and custom ranges. Users would also like to be able to select what time period data will be rolled up to, days, weeks, months, years. For the canned date ranges provided, the roll up will default to the following:
7 days - day
14 days - day
30 days - day
90 days - week?
last year - month
all time - year
custom range - year

**Comment by pkarman** [comment]
per @sandikbarr this is done.
