### ISSUE TITLE
Look at competitor metrics and analytics

### ISSUE THREAD

**Issue by kookster** [PRX/chart.prx.org#9]
@kookster commented on [Fri Oct 07 2016](https://github.com/PRX/cms.prx.org/issues/173)

**Comment by sandikbarr** [comment]
I only have a login for SoundCloud, but we should also see about accessing Blubrry, Podtrac, Spotify to look at what they are offering.

**Comment by sandikbarr** [comment]
Podtrac provides 
* Dashboard:
    * Total downloads of all time
    * Aggregate total downloads by Publisher. I don’t see how this would be different than aggregating total downloads if the user had more than one series
    * Total downloads by series/show
    * Total downloads of 10 most recent episodes
* Unique Monthly Audience - all episodes aggregated to monthly download numbers
* Graphs shown appear to be for entire series (and they are Flash, ew)
* Podcast measurement reports
    * Ranges
        * Daily is the past 7 days, current day not included)
        * Weekly is past 6 weeks, current week included as partial week
        * Monthly is past 6 months, current month included
        * Quarterly is past 6 quarters, current quarter included
    * Feeds
        * Since podtrac allows you to register multiple feeds for the same podcast, it also allows you to split out reports by those feeds or see an aggregate of all feeds
    * By Episode
        * Daily, Weekly, Monthly, and Quarterly unique downloads by episode. Shows all episodes in a single page, split out and rolled up by month released, with past X periods of download data 
    * By Source (User Agent)
        * Daily, Weekly, Monthly, and Quarterly unique downloads by source
        * There is a section strictly for iTunes sources and a section for Other Sources such as Stitcher, NPR One, and Zune
    * By Country
        * Daily, Weekly, Monthly, and Quarterly unique downloads by Country
        * Country is the only geographic info
        * Shows all countries that have in a long list
        * There is an “Other” country in the list
* Podcast Audience Survey Reports
    * Listener Surveys on demographics, business, behavior, satisfaction, likes and dislikes
    * Split out by Series
    * Can show All Time or yearly survey data
* Shows by the same producer have separate podtrac accounts, e.g. TWWW is separate from Song Exploder
